
apiVersion: v1
kind: Service
metadata:
  name: spring-welcome-app
  labels:
    app: spring-welcome-app
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-welcome-app